// Targeted by JavaCPP version 1.5.4-SNAPSHOT: DO NOT EDIT THIS FILE

package com.adonmo.meos;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class MeosLibrary extends com.adonmo.meos.MeosLibraryConfig {
    static { Loader.load(); }

// Parsed from meos/types/box/TBox.hpp

// #pragma once

// #include <chrono>
// #include <cmath>
// #include <string>

/**
 * \brief %Temporal box - bounding box with value and/or time dimensions.
 */
@Namespace("meos") @NoOffset public static class TBox extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public TBox(Pointer p) { super(p); }

  public TBox(double xmin, double xmax) { super((Pointer)null); allocate(xmin, xmax); }
  private native void allocate(double xmin, double xmax);

  public native double xmin();
  public native double xmax();

  
  
  
  
  
  

  
  
}

  // namespace meos


}
