name: Tests

on: [push]

env:
  CMAKE_VERSION: 3.16.2
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install GEOS
        run: sudo apt-get -y update && sudo apt-get -y install libgeos-dev

      - name: Get MEOS source code
        working-directory: ${{runner.workspace}}
        run: git clone https://github.com/adonmo/meos

      - name: Configure CMake for tests
        working-directory: ${{runner.workspace}}/meos
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build GEOS
        working-directory: ${{runner.workspace}}/meos
        run: cmake --build build --config $BUILD_TYPE

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run tests with Gradle
        run: ./gradlew test
